- name: OmniEdge for Github Action 
   uses: omniedgeio/github-action@v1 
   with: 
       securitykey: ${{ secrets.OMNIEDGE_SECURITY_KEY }} 
       virtualnetworkid: ${{ secrets.OMNIEDGE_VIRTUALNETWORK_ID }}
